apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bagman
  name: bagman
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bagman
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: bagman
    spec:
      containers:
        - env:
            - name: DOORMAN_URL
              value: http://doorman:8080
            - name: OTLP_METRICS_EXPORT_URL
              value: {{ .Values.otel.metrics.url | default "http://otel-collector:4318/v1/metrics" | quote }}
            - name: OTLP_TRACES_EXPORT_URL
              value: {{ .Values.otel.traces.url | default "http://otel-collector:4318/v1/traces" | quote }}
            {{- if and (.Values.grafana.instanceId) (.Values.grafana.apiKey)}}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: Authorization=Basic {{ printf "%d:%s" .Values.grafana.instanceId .Values.grafana.apiKey | b64enc }}
            {{ end }}
            {{ if .Values.redis.url }}
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
            {{ end }}
          image: ghcr.io/sheunglaili/bagman:0.0.5
          name: bagman
          ports:
            - containerPort: 8080
            - containerPort: 9464
          resources: {}
      restartPolicy: Always
status: {}
