apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: doorman
  name: doorman
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: doorman
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: doorman
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: {{ .Values.redis.host | default "redis" | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | default "6379" | quote }}
            {{- if .Values.redis.username }}
            - name: REDIS_USERNAME
              value: {{ .Values.redis.username | quote }}
            {{ end }}
            {{- if .Values.redis.password }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password | quote }}
            {{ end }}
            {{- if .Values.redis.tls }}
            - name: REDIS_TLS
              value: {{ .Values.redis.tls | quote }}
            {{ end }}
          image: ghcr.io/sheunglaili/doorman:0.3.1
          name: doorman
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/doorman/doorman.yaml
              name: doorman-cm0
              subPath: doorman.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: doorman.yaml
                path: doorman.yaml
            name: doorman-cm0
          name: doorman-cm0
status: {}
