{{- if eq .Values.grafana.install true }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mimir
  name: mimir
spec:
  ports:
    - name: "9009"
      port: 9009
      targetPort: 9009
  selector:
    io.kompose.service: mimir
status:
  loadBalancer: {}
{{ end }}