{{- if eq .Values.otel.install true }}
apiVersion: v1
data:
  otel-collector-config.yaml: |-
    receivers:
      # Data sources: traces, metrics, logs
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlphttp:
        traces_endpoint: {{ .Values.grafana.tempo.url | default "http://tempo:4318/v1/traces" | quote }}
        metrics_endpoint: {{ .Values.grafana.mimir.url | default "http://mimir:9009/otlp/v1/metrics" | quote }}

    service: 
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
        metrics: 
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector-cm0
{{ end }}