{{- if eq .Values.redis.install true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        traefik.enable: "false"
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "20"
            - "1"
            - --loglevel
            - verbose
          image: redis:7
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
{{ end }}